akka/akka-stream-contrib

mqtt/build.sbt, mqtt/src/main/scala/Mqtt.scala, mqtt/src/main/scala/MqttSource.scala, mqtt/src/test/scala/MqttSourceSpec.scala
Mqtt Akka Stream Source implementation which uses Async Paho Client under the hood.
=> Mqtt Source

amqp/build.sbt, build.sbt, contrib/build.sbt, mqtt/build.sbt, mqtt/src/main/scala/Mqtt.scala, mqtt/src/main/scala/MqttSource.scala, mqtt/src/test/scala/MqttSourceSpec.scala
Add backpressure signalt to MQTT library by blocking library thread, when the internal buffer becomes full.
Also add support for multiple materialization by moving subscription future inside of create logic.
=> Backpressure and multiple materialzation

src/main/scala/akka/stream/contrib/Sample.scala, src/test/scala/akka/stream/contrib/SampleSpec.scala
ref #21 
I started by a simple implementation. 
questions:
- I tried `def apply(maxStep:Int, random:Random=Random)` for random sampling, but looks wired. Any suggestion?
- need to implement time-based sampling?
Feel free to review or close it.
=> WIP: add sample stage

.travis.yml, build.sbt, cassandra/README.md, cassandra/build.sbt, cassandra/src/main/scala/akka/stream/contrib/cassandra/CassandraSource.scala, cassandra/src/test/scala/akka/stream/contrib/cassandra/CassandraSourceSpec.scala, cassandra/src/test/scala/akka/stream/contrib/cassandra/README.txt
This PR provides a way to transform a Cassandra's ResultSet into a Akka Stream's Source, i.e. it lets you stream the result of a Cassandra query.
Example:
```scala
import akka.actor.ActorSystem
import akka.actor.stream.ActorMaterializer
import akka.stream.contrib.cassandra.CassandraSource
import com.datastax.driver.core.{SimpleStatement, Cluster}
implicit val system = ActorSystem()
implicit val mat = ActorMaterializer()
val cluster = Cluster.builder.addContactPoint("127.0.0.1").withPort(9042).build
implicit val session = cluster.connect()
val stmt = new SimpleStatement("SELECT * FROM akka_stream_test.test")
val cassSource: Source[Row, NotUsed] = CassandraSource(stmt)
```
=> Add Cassandra Source

contrib/src/main/scala/akka/stream/contrib/Valve.scala, contrib/src/test/scala/akka/stream/contrib/ValveSpec.scala, project/Common.scala
* development should be done with Scala 2.11 so that new
features (e.g. in library) are not accidentilly used
=> use Scala 2.11 as default

contrib/src/main/scala/akka/stream/contrib/Pulse.scala, contrib/src/main/scala/akka/stream/contrib/TimeWindow.scala, contrib/src/test/scala/akka/stream/contrib/PulseSpec.scala, contrib/src/test/scala/akka/stream/contrib/TimeWindowSpec.scala, contrib/src/test/scala/akka/stream/contrib/ValveSpec.scala
Please refer to https://github.com/akka/akka/issues/22420 where motivation behind elements being committed was discussed. It was suggested there ( https://github.com/akka/akka/issues/22420#issuecomment-284156185 ) that a PR containing this work should go to contrib repository. At the cost of violating DRY, I am pasting relevant elements of the original issue here for easier reference:
> I couldn't find any existing stage to accomplish simple time-window processing where data is aggregated for predefined amount of time and the computed aggregate is emitted once per this time. While conflateWithSeed fits the "aggregation" part of processing very nicely, I couldn't find any element that could steer the back-pressure to pull the aggregate once in a while and push it downstream. delay is …
=> A potentially useful akka-stream stage for time-window processing

.travis.yml, project/Common.scala
As `akka.series` is not a valid env var name: https://github.com/akka/alpakka/commit/095f24e0e89f0f6bb0fc1ffd797b71ba28621b77#commitcomment-22195861
=> Fix akka series env var name

contrib/build.sbt, contrib/src/test/scala/akka/stream/contrib/ValveSpec.scala
=> Dilate ScalaTest future timeout to 600ms (fixes #106)

contrib/src/test/scala/akka/stream/contrib/BaseStreamSpec.scala, contrib/src/test/scala/akka/stream/contrib/TimeWindowSpec.scala, project/Common.scala
An attempt to fix a flaky TimeWindow spec #104
TimeWindow uses conflate, therefore we should not test the contents of elements after the conflate stage, because the number of aggregate function invocations is not stable. 
This PR changes the test so it does not assert the outgoing elements. It also tests the Pulse stage by controlling the scheduler.
=> #104 Use mock scheduler when testing Pulse stage

contrib/src/test/resources/application.conf, contrib/src/test/scala/akka/stream/contrib/UnfoldFlowSpec.scala
Tests are now deterministic, and not affected by race conditions.
Ref: #108
=> converted tests to use flow from publisher & subscriber instead of killswitch

contrib/src/main/scala/akka/stream/contrib/IntervalBasedRateLimiter.scala, contrib/src/test/scala/akka/stream/contrib/IntervalBasedRateLimiterSpec.scala
This is a continuation of PR #102 where I proposed a custom stage which emits elements with a minimum time interval.
This PR introduces `IntervalBasedRateLimiter` implementation based on #90.
For more details and motivation see #101.
=> An interval-based rate limiter #101

contrib/src/test/scala/akka/stream/contrib/IntervalBasedRateLimiterSpec.scala
AFAICS we don't really promise to batch into exactly
`numOfElements / maxBatchSize` batches, but strictly
speaking just at least that. We see it spill over by
1 (4 instead of 3) batches for the 'frequency is very high' test.
Refs #125
=> Allow rate limiter to spill over (#125)

contrib/src/main/resources/reference.conf, contrib/src/main/scala/akka/stream/contrib/Retry.scala, contrib/src/test/scala/akka/stream/contrib/RetrySpec.scala
This pull request solves issue #86 
The suggested code of `RetryConcatCoordinator` now process more than 1 element at a given time.
It contains 2 queues which buffer elements for future emitting. 
In order to avoid finishing the stream too early (i.e., elements are still being processed within the stream but upstream signaled termination), a counter is maintained.
=> fix issue #86

contrib/src/main/scala/akka/stream/contrib/KeepAliveConcat.scala, contrib/src/test/scala/akka/stream/contrib/KeepAliveConcatSpec.scala
This stage helps when we want the keep alive functionality, but without injecting default elements (e.g. zeroes), and, instead, maintain a buffer and inject elements from it when the upstream is slow.
Example:
input elements: `[1,2,3]`
`keepAlive` (existing): `[1,2,0,0,3]` (no buffer, emit 0 to maitain the emit rate)
`keepAliveConcat` (this PR): `[1,2,3]` (2 and 3 were buffered and used to maintain the rate)
Initially, this PR was opened against the Akka project: https://github.com/akka/akka/pull/24658
=> Add keep alive from buffer graph stage

project/Publish.scala
Also `dynverSonatypeSnapshots := true` was required to append `SNAPSHOT` to the version string because that is what sonatype snapshots repository requires.
=> Fix snapshot detection

contrib/src/main/scala/akka/stream/contrib/SourceRepeatEval.scala, contrib/src/test/scala/akka/stream/contrib/SourceRepeatEvalSpec.scala
People often need this and I think there is an advantage to having this as opposed to always doing
```scala
Source.repeat(()).map(_ => ...)
```
=> Add by-name version of Source.repeat

contrib/src/main/scala/akka/stream/contrib/FeedbackLoop.scala, contrib/src/test/scala/akka/stream/contrib/FeedbackLoopSpec.scala
The motivation is to provide a safe way to create feedback loops. Deadlock is never the desired behavior, yet they are tricky to avoid when creating cycles manually.
The trick to avoid deadlocks is to never backpressure the feedback loop (and prefer failure when the buffer overflows).
=> Add FeedbackLoop operator, a deadlock-free way of introducing cycles.

.travis.yml, project/Common.scala
No longer require sources to compile with Akka 2.4 series.
@raboof in #151:
> I think it would be OK to drop support for Akka 2.4 in this library, given 2.5 has now been out for almost 2 years
Generally, it seems OK to me to require some minimal Akka version for each akka-stream-contrib version, as thanks to Akka's backward compatibility users should be able to safely update their Akka version as well.
=> Drop support for Akka 2.4.x.

build.sbt
The default is derived from the organization name, which is not correct. 
Fixes #156
=> Fix sonatype profile name

.travis.yml, build.sbt, src/main/scala/akka/stream/contrib/AccumulateWhileUnchanged.scala
Add support for Scala 2.13.
Prepares for #147.
* Add Scala 2.13.0 to cross version list
* Modify compiler flags to be compatible across different Scala versions
* Remove obsolete usage of `Unit` term
* Update scalatest to 3.0.8
* Update akka to 2.5.23
* Update akka-mock-scheduler to 0.5.5
* Change jdk from oraclejdk8 to openjdk8 in Travis CI as oraclejdk8 seems to have stopped working
Scala 2.13.0 was released on June 11.
=> Build for Scala 2.13

.travis.yml
Moves publishing and releasing to separate jobs in separate stages so that these tasks would not interfere with each other.
After adding publishing for 2.13 all artifacts were published across more than one Sonatype repository. We could use `sonatypeReleaseAll` but that could release repositories from other projects, that use the same profile-id.
=> Publish and release for each Scala version separately

.travis.yml, build.sbt
Use alias, instead of multiple tasks.
Fixes #161
Cross-building multiple commands needs an command alias.
=> Add alias for releasing commands

.travis.yml
Changes to the legacy cross build command, as we might be hitting https://github.com/sbt/sbt/issues/4599
=> Switch to legacy cross building

src/main/scala/akka/stream/contrib/TokenThrottle.scala, src/test/scala/akka/stream/contrib/TokenThrottleSpec.scala
Allows to use a centrally managed token bucket that distributes tokens
to multiple flows. Provides both a GraphStage for this kind of setup as
well as a Flow factory for a simpler setup where tokens are provided via
a Source.
Fixes #166
=> Introduce token throttle flow

src/main/scala/akka/stream/contrib/MergeByIndex.scala, src/test/scala/akka/stream/contrib/MergeByIndexSpec.scala
This pull requests proposes a new `MergeByIndex` stage for merging multiple upstreams by index (i.e. by total order). It supports a custom total order over incoming elements, and offers a convenience constructor for tuples created via `.zipWithIndex`. The stage requires a total ordering, and as such, fails fast as soon as it detects that the index is not strict monotonically increasing. `MergeByIndex` can handle index omissions that can be created by upstreams filtering out elements that shouldn't be further processed. It doesn't yet support eager completion; currently, it will complete only after all its upstreams completed and internally buffered elements are emitted.
Internally, `MergeByIndex` works by keeping track of the next expected index, starting at zero. It initially pulls from …
=> MergeByIndex fan-in stage

build.sbt, src/main/scala/akka/stream/contrib/Implicits.scala, src/main/scala/akka/stream/contrib/latencyTimer.scala, src/test/scala/akka/stream/contrib/LatencyTimerSpec.scala
LatencyTimer provides a operator which can wrap any Flow-Shape and measure how long each element took.
The operator uses the following shape
I -> O, TimedResult[O] when wrapping a Flow[I,O]
The TimedResult contains the wrapped flows result as well in case further logic is needed. Example would be to distinguish between different metrics based on the result of the wrapped flow.
The operator does only support flows which are preserving the order, so no async should be done inside (only mapAsync).
I could not come up with a better name than LatencyTimer and measureLatency in the DSL. Basically "Timed" would have been better but this is already used by another operator.
References:
https://discuss.lightbend.com/t/ideas-on-how-to-implement-a-latency-monitor-which-wraps-a-flow/5714/5
=> Introduce LatencyTimer operator.

src/main/scala/akka/stream/contrib/AccumulateWhileUnchanged.scala, src/test/scala/akka/stream/contrib/AccumulateWhileUnchangedSpec.scala
If `onTimer()` is called when `buffer` is not empty, it will `push()`
results but the `pull(in)` request will not be canceled. If additional
upstream elements arrive with a different `nextState` which would cause
`pushResults()` to be called again before the downstream indicates demand
via `onPull()`, then `nextElement` would be dropped.
Avoid pushing again after push() from onTimer() until onPull() is called
again to indicate downstream demand. This avoids dropping elements when
pushResults() is called but `out` is not available.
In case a similar issue occurs again, add a `require()` check which will
throw if nextElement would be discarded.
Note that the use of the `downstreamWaiting` flag is very similar to that of
`TwoBuffer` in the [Custom stream processing - Rate decoupled …
=> AccumulateWhileUnchanged: stop pull() after onTimer()
