- build.sbt
- src/main/scala/akka/stream/contrib/Accumulate.scala
- src/main/scala/akka/stream/contrib/LastElement.scala
- src/test/scala/akka/stream/contrib/AccumulateSpec.scala
- src/test/scala/akka/stream/contrib/BaseStreamSpec.scala
- src/test/scala/akka/stream/contrib/LastElementSpec.scala
- Copy src from hseeberger/commons-akka-stream, add dep on ScalaTest
- Remove unnecessary package object
- Rename package to akka.stream.contrib
> Add Accumulate and LastElement (closes #3)

- src/main/scala/akka/stream/contrib/ZipInputStreamSource.scala
- src/test/scala/akka/stream/contrib/ZipInputStreamSourceSpec.scala
> A Source for zip files (fixes #8)

- src/main/scala/akka/stream/contrib/ZipInputStreamSource.scala
- src/test/scala/akka/stream/contrib/ZipInputStreamSourceSpec.scala
> ZipInputStreamSource: Mark ZipEntryData as final (closes #12)

- .gitignore
- src/main/scala/akka/stream/contrib/PartitionWith.scala
- src/test/scala/akka/stream/contrib/PartitionWithSpec.scala
> PartitionWith stage added

- src/main/scala/akka/stream/contrib/AccumulateWhileUnchanged.scala
- src/test/scala/akka/stream/contrib/AccumulateWhileUnchangedSpec.scala
> Add AccumulateWhileUnchanged

- src/main/scala/akka/stream/contrib/Retry.scala
- src/test/scala/akka/stream/contrib/RetrySpec.scala
PR for https://github.com/akka/akka-stream-contrib/issues/25
> Retry flows API

- mqtt/build.sbt
- mqtt/src/main/scala/Mqtt.scala
- mqtt/src/main/scala/MqttSource.scala
- mqtt/src/test/scala/MqttSourceSpec.scala
Refactored the Mqtt spec so that the test may not be  broken on CI. And hence Resolved the issue in the PR #40
> Refactored the MqttSpec and added the basic functionality

- mqtt/src/main/scala/Mqtt.scala
- mqtt/src/main/scala/MqttSource.scala
- mqtt/src/test/scala/MqttSourceSpec.scala
* remove race condition between connect and message handler set
* final case classes
* make handlers abstract, instead of asyncCallback getters
* make internal implementation private to the package
* abstract over implicit argument lists
> Address Mqtt source review feedback

- contrib/build.sbt
- contrib/src/main/scala/akka/stream/contrib/Coroner.scala
- contrib/src/main/scala/akka/stream/contrib/TestKit.scala
See https://github.com/akka/akka/issues/21028
> Fix akka#21028 - Publish de Akka Stream TestKit utilities

- .gitignore
- contrib/src/main/resources/reference.conf
- contrib/src/main/scala/akka/stream/contrib/SourceGen.scala
- contrib/src/main/scala/akka/stream/contrib/UnfoldFlow.scala
- contrib/src/test/scala/akka/stream/contrib/UnfoldFlowSpec.scala
PR for https://github.com/akka/akka-stream-contrib/issues/32
this is still a WIP. no tests & complete docs yet.
also, concerns raised in the issue need to be discussed.
> unfoldFlow & unfoldFlowWith Source generators added

- build.sbt
- project/Common.scala
- xmlparser/build.sbt
- xmlparser/src/main/scala/com/drewhk/stream/xml/Xml.scala
- xmlparser/src/test/scala/com/drewhk/stream/xml/SubsliceTest.scala
- xmlparser/src/test/scala/com/drewhk/stream/xml/XmlCoalesceTest.scala
- xmlparser/src/test/scala/com/drewhk/stream/xml/XmlProcessingTest.scala
Migrated from https://github.com/drewhk/akka-xml-stream
> Streaming XML parser and utilities.

- mqtt/src/main/scala/Mqtt.scala
- mqtt/src/test/scala/MqttSourceSpec.scala
MQTT public brokers (such as the one from TheThingsNetwork used with a lot of IoT devices) require a login/password.
> Add optional authentication to MQTT connections

- cassandra/src/test/scala/akka/stream/contrib/cassandra/CassandraSourceSpec.scala
- cassandra/src/test/scala/akka/stream/contrib/cassandra/README.txt
> Extend timeout for Cassandra spec

- contrib/src/main/scala/akka/stream/contrib/Valve.scala
- contrib/src/test/scala/akka/stream/contrib/ValveSpec.scala
- implements a valve to control a flow through a switch
> Valve to control a flow (open/close)

- contrib/build.sbt
> Make akka-stream-testkit dependency provided (closes #82)

- contrib/src/main/scala/akka/stream/contrib/Valve.scala
- contrib/src/test/scala/akka/stream/contrib/ValveSpec.scala
- fix the reported bug https://github.com/akka/akka-stream-contrib/issues/84
> Fix Valve component pulls port (valve.in) twice

- contrib/src/main/scala/akka/stream/contrib/DelayFlow.scala
- contrib/src/test/scala/akka/stream/contrib/DelayFlowSpec.scala
Implementation of flexible DelayStage with ability to create your own delay strategies with different delay policies. 
Refs #89
> DelayFlow with flexible DelayStrategy implementation #89

- contrib/src/main/scala/akka/stream/contrib/Valve.scala
- contrib/src/test/scala/akka/stream/contrib/ValveSpec.scala
As described in #116 there is a getMode method on the `ValveSwitch` now.
> Add .getMode to the the valve swich to be able to check the current state

- .travis.yml
- RELEASING.md
Hmm, looks like we need to add a way to set the sonatype credentials via
environment variables? And document that you'll have to close the repo
from the sonatype UI?
> Deploy from travis

- README.md
So it has the same badge markup format as Alpakka and others.
> Consolidate the format of README

- contrib/src/main/scala/akka/stream/contrib/PagedSource.scala
- contrib/src/test/scala/akka/stream/contrib/PagedSourceSpec.scala
this is an implementation of daniels idea issue #93
> implement PagedSource

- contrib/src/main/java/akka/stream/contrib/DirectoryChanges.java
- contrib/src/main/java/akka/stream/contrib/FileTailSource.java
as they are part of Alpakka
See #132
> Deprecate DirectoryChanges and FileTailSource 

- contrib/src/main/scala/akka/stream/contrib/PassThroughFlow.scala
- contrib/src/test/scala/akka/stream/contrib/PassThroughFlowSpec.scala
As discussed here: https://discuss.lightbend.com/t/passing-stream-elements-into-and-over-flow/2536
cc @2m
> Add PassThrough Flow

- contrib/src/main/scala/akka/stream/contrib/AccumulateWhileUnchanged.scala
- contrib/src/test/scala/akka/stream/contrib/AccumulateWhileUnchangedSpec.scala
See issue #144 
Any feedback is welcome
> Add maxElements and maxDuration parameters to AccumulateWhileUnchanged

- contrib/src/test/scala/akka/stream/contrib/PartitionWithSpec.scala
Test that values belonging to one partition can flow without the other outlet being pulled.
> Additional PartitionWith test

- contrib/src/main/scala/akka/stream/contrib/PartitionWith.scala
- contrib/src/test/scala/akka/stream/contrib/PartitionWithSpec.scala
When one downstream of `PartitionWith` cancels, events to the other downstream should keep flowing. This is consistent with what `Partition` does.
> PartitionWith: add eagerCancel parameter.

- src/main/scala/akka/stream/contrib/TokenThrottle.scala
- src/test/scala/akka/stream/contrib/TokenThrottleSpec.scala
Fixes #168
Stage now completes if an element was buffered and tokens were available, but too few to emit the element, and the token source would complete.
Stage now pre-fetches tokens if the downstream did not yet pull, but the currently buffered element is too expensive to emit with the currently available token budget.
> Fix token throttle completion issue and improve token pre-fetching

- .travis.yml
- build.sbt
> Upgrade akka to 2.6.0 and drop scala 2.11.x

- src/test/scala/akka/stream/contrib/AccumulateWhileUnchangedSpec.scala
> Make test less timing-sensitive

- .travis.yml
- README.md
> Remove publishing / move to travis-ci.com

- src/main/scala/akka/stream/contrib/Valve.scala
- src/test/scala/akka/stream/contrib/ValveSpec.scala
Once the valve stage has been stopped, the future returned by `getMode`
used to never complete (an async callback is invoked with a `Promise`,
but the callback action is never process once the stage is completed).
By using `invokeWithFeedback` instead of `invoke`, we can be sure that
that future returned by `getMode` will either fail if the valve is
already stopped or else will be processed by the valve.
References #119
> Valve: `getMode` fails after the stage is stopped
